#pragma once

/*#define COM_CONTROL_DEFAULT 1000*/

enum COMControlFullList
{
  //默认的填充为Defualt
  COM_CONTROL_DEFAULT = 100,
  COM_CONTROL_WAIT_TILL_LINE_0,
  COM_CONTROL_WAIT_TILL_LINE_1,
  COM_CONTROL_WAIT_TILL_LINE_2,
  COM_CONTROL_WAIT_TILL_LINE_3,
  COM_CONTROL_WAIT_TILL_LINE_4,
  COM_CONTROL_WAIT_TILL_LINE_5,
  COM_CONTROL_WAIT_TILL_LINE_6,
  COM_CONTROL_WAIT_TILL_LINE_7,
  COM_CONTROL_WAIT_TILL_LINE_8,
  COM_CONTROL_WAIT_TILL_LINE_9,
  COM_CONTROL_WAIT_TILL_LINE_10,
  COM_CONTROL_WAIT_TILL_LINE_11,
  COM_CONTROL_WAIT_TILL_LINE_12,
  COM_CONTROL_WAIT_TILL_LINE_13,
  COM_CONTROL_WAIT_TILL_LINE_14,
  COM_CONTROL_WAIT_TILL_LINE_15,
  COM_CONTROL_WAIT_TILL_LINE_16,
  COM_CONTROL_WAIT_TILL_LINE_17,
  COM_CONTROL_WAIT_TILL_LINE_18,
  COM_CONTROL_WAIT_TILL_LINE_19,
  COM_CONTROL_WAIT_TILL_LINE_20,
  COM_CONTROL_WAIT_TILL_LINE_21,
  COM_CONTROL_WAIT_TILL_LINE_22, //不可能是22，但是还是留着，以备以后用
  //以后行数多了，会有更多情况，但是旋转都先默认为发生在22以内，具体还要修改translater
  COM_CONTROL_ROTATE,
  COM_CONTROL_MOVE_LEFT,
  COM_CONTROL_MOVE_RIGHT,
  COM_CONTROL_MOVE_STRAIGT_DOWN
};