#pragma once

int get_the_best_rotate_and_coord__COM_control_AI(Param *pstParam,
  int *pnCoordiX, int *pnCoordiY, int *pnRotationTime);
int translate_COM_cmd_to_action__COM_control_AI(Param *pstParam, int nCmd,
  int *pnControlFlag, bool *pbIsSessionEndedCOM);

#define COM_AI_TETRIS_SPACE_MAX_SCORE 2540
#define COM_AI_TETRIS_SPACE_SCORE_OUT_REACH 2530
#define COM_AI_TETRIS_SPACE_SCORE_CONTAIN_WALL 2520
#define COM_AI_TETRIS_SPACE_SCORE_CONTAIN_SOLID_BLOCK 2510
#define COM_AI_TETRIS_SPACE_SCORE_SOLID_BLOCK_ABOVE 2500
#define COM_AI_TETRIS_SPACE_MIN_HEIGHT_DEFAULT \
  (COM_AI_TETRIS_SPACE_MAX_SCORE + 1)
#define COM_AI_TETRIS_SPACE_SCORE_SAPCE_BELOW 2490

/*
#define COM_AI_TETRIS_SPACE_MAX_SCORE 0
#define COM_AI_TETRIS_SPACE_SCORE_OUT_REACH 0
#define COM_AI_TETRIS_SPACE_SCORE_CONTAIN_WALL 0
#define COM_AI_TETRIS_SPACE_SCORE_CONTAIN_SOLID_BLOCK 0
#define COM_AI_TETRIS_SPACE_MIN_HEIGHT_DEFAULT 0*/